name:                Haskyph
version:             0.1.0.0
github:              "WolfgangTS/Haskyph"
license:             BSD3
author:              "Noe Nogueira Martins"
maintainer:          "lobo.noe@gmail.com"
copyright:           "2018 Noe Nogueira Martins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/WolfgangTS/Haskyph#readme>

dependencies:
- base >= 4.7 && < 5
- gloss == 1.*
- lens == 4.16.1 

library:
  source-dirs: src

executables:
  Haskyph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskyph

tests:
  Haskyph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskyph
